version: '3.3'
 
services:
   wordpress:
     container_name: "wordpress"
     image: wordpress:latest
     depends_on:
       - db
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     ports:
     - "80:80"
     volumes:
       - ./wordpress:/var/www/html
 
   db:
     image: mysql:5.7
     container_name: "mysql57"
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   pma:
     container_name: "pma"
     image: phpmyadmin/phpmyadmin:latest
     environment:
       PMA_HOST: db
     ports:
     - "8080:80"
     restart: always
     links:
       - db
 
 
volumes:
   db_data:
   wordpress:
